### ISSUE TITLE
TRB template 2019

### ISSUE THREAD

**Issue by DeepakIngole** [chiehrosswang/TRB_LaTeX_tex#12]
Hi, 

Thank you for solving my previous issue. If you don't mind I want to ask the following question. 
Is this template according to the TRB 2019 rules (http://onlinepubs.trb.org/onlinepubs/am/infoforauthors.pdf), which says Figures will not be counted, font: times roman 10 pt, page: 8.5 x 11 (not A4), etc. 

This is not an issue but wanted to confirm. 
Thanks.

**Comment by DeepakIngole** [comment]
While writing a paper I found that I need to give space (\newline,\\, etc.) between text and \begin{equation} and again one line space after \end{equation} then only we can see space otherwise equation starts immediately below the text. Why is this so? In normal article or paper, we can see space even without giving manual space. Thank you.

**Comment by chiehrosswang** [comment]
Regarding the TRB 2019 rules, yes, I've made updates last week to reflect the changes in 2019.  The total word count in the updated version should only count Tables towards the final word count.  Everything else should remain the same as previous years.  Do you want to open the newline issue as a separate issue (since it's irrelevant to this issue)?
