### ISSUE TITLE
Space before and after equation

### ISSUE THREAD

**Issue by DeepakIngole** [chiehrosswang/TRB_LaTeX_tex#13]
While writing a paper I found that I need to give space (\newline,\, etc.) between text and \begin{equation} and again one line space after \end{equation} then only we can see space otherwise equation starts immediately below the text. Why is this so? In normal article or paper, we can see space even without giving manual space. Thank you.

**Comment by DeepakIngole** [comment]
It worked as expected by commenting the lines of the equation in trbunofficial.cls (line no. 93 -102).

**Comment by gregmacfarlane** [comment]
Wanna send a PR deleting those lines? (Not just commenting them)

**Comment by chiehrosswang** [comment]
TRB did not really specify whether or not there should be an extra line between texts and equations.  I think this issue is more of a personal preference - if we remove lines 93-102 from trbunofficial.cls, the equations look more spaced out; if we keep them, the questions look tighter.  Personally, I'd like to keep it the way it is.
